### ISSUE TITLE
`menu` script blocked in MacOS Catalina

### ISSUE THREAD

**Issue by codeinthehole** [BenziAhamed/Menu-Bar-Search#7]
After installing the workflow and trying to use it, I get this error:
![image](https://user-images.githubusercontent.com/80975/88273621-5f29e100-ccd2-11ea-9c1b-6183071ff3e5.png)

v1.6 of workflow
MacOS v10.15.5

Does this require a new version to fix?

**Comment by eyemyth** [comment]
Try to use the workflow, and when the dialog appears, open System Preferences -> Security and Privacy. Under the General tab, towards the bottom you should see '"menu" was blocked from use because it is not from an identified developer'

Just click the Open Anyway button and you should be able to use it again

**Comment by codeinthehole** [comment]
Thanks - that did the trick.

**Comment by flxs** [comment]
Another way to solve this:

Open Alfred preferences, right-click on the workflow, Open in Terminal, `xattr -rd com.apple.quarantine menu` – this will remove the quarantine attribute.
