### ISSUE TITLE
Allow larger quantity of sub-menu items (possibly per app through settings file) 

### ISSUE THREAD

**Issue by NeighNeighNeigh** [BenziAhamed/Menu-Bar-Search#9]
Hi thanks for this, Ive been using it daily for some time. I do animation and use some apps which have large numbers of menu entries. Sadly menu bar search fails on many of these items as a result of the limitation you mention in the Airmail bug post:

"there is a limit of 40 sub-menu items it will display (mainly done for speed)."

Would it be possible to change this limitation for instances where the workflow fails to cover all menu items?

**Comment by BenziAhamed** [comment]
I'll time to update settings file to allow for more sub-menu items. (It would be ideal since you can control it per app).

That said, if you are feeling adventurous to modify the workflow a bit, this is something you can try out: 

- Open the workflow in Alfred, and select the **Script Filter** titled `m`
<img width="1361" alt="Screenshot 2020-10-21 at 4 42 50 PM" src="https://user-images.githubusercontent.com/1894423/96712575-fcbdab00-13bc-11eb-998a-1acfa95a5ba9.png">

- Open up the selected Script Filter (press Enter or Double Tap), and you should see something like:
<img width="1361" alt="Screenshot 2020-10-21 at 4 42 58 PM" src="https://user-images.githubusercontent.com/1894423/96712585-ffb89b80-13bc-11eb-8abf-8b53a6745e70.png">

- Modify the script to `./menu -async -cache 5 -max-children 200 -query "{query}"`, with the addition of `-max-children 200` to the command. Note that this will affect all apps.
<img width="1361" alt="Screenshot 2020-10-21 at 4 43 26 PM" src="https://user-images.githubusercontent.com/1894423/96712603-05ae7c80-13bd-11eb-9c70-65411bf2c30a.png">

That should now allow you to have up to 200 sub-menu items listed. I'm not sure if this will slow things a lot for you, but worth a try.

**Comment by PicoNano** [comment]
Hey Benzi,
Thanks so much for taking onboard this feedback and for providing such easy to follow instructions for a right-now-solution. I have so much love for this workflow. It is so valuable in my day to day operations.
